config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :recipes, only: [ :index, :show ]
  resources :ingredients, only: [ :index, :show ]
  get "/api/:query", to: 'recipes#api', as: :api
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  validates :energy, presence: true
  validates :carbs, presence: true
  validates :fat, presence: true
  validates :fibre, presence: true
  validates :protein, presence: true
end

app/models/nutrient.rb
class Nutrient < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  validates :unit, presence: true, uniqueness: true
end

app/models/rda.rb
class Rda < ApplicationRecord
  belongs_to :nutrient
  validates :name, presence: true
  validates :amount, presence: true, numericality: { greater_than: 0 }
  validates :gender, presence: true, inclusion: { in: [ "male", "female" ] }
  validates :age, presence: true
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  validates :name, presence: true
  validates :category, presence: true
  validates :url, presence: true, uniqueness: true
  validates :energy, presence: true, numericality: true
  validates :carbs, presence: true, numericality: true
  validates :fat, presence: true, numericality: true
  validates :protein, presence: true, numericality: true
  validates :data, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :index ]

  def index
    url = "https://api.edamam.com/api/food-database/parser?app_id=#{ENV['EDAMAM_APP_ID']}&app_key=#{ENV['EDAMAM_API_KEY']}&ingr=#{params[:query]}&health=vegan"
    json = RestClient.get(url)
    results = JSON.parse(json)
    @ingredients = []
    results["hints"].each do |result|
      ingredient = Ingredient.new({
        name: result["food"]["label"],
        energy: result["food"]["nutrients"]["ENERC_KCAL"],
        carbs: result["food"]["nutrients"]["CHOCDF"],
        fat: result["food"]["nutrients"]["FAT"],
        protein: result["food"]["nutrients"]["PROCNT"],
        fibre: result["food"]["nutrients"]["FIBTG"]
      })
      @ingredients << ingredient if ingredient.valid? && result["food"]["categoryLabel"] == "food"
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :index, :api ]
  before_action :find_recipe, only: [ :index, :api ]

  def index
    recipe_params = []
    Recipe.all.each do |recipe|
      recipe_params << [ recipe.carbs, recipe.fat, recipe.protein ]
    end
    index = Ngt::Index.new(3)
    index.batch_insert(recipe_params)
    query = recipe_params[@recipe.id - 1]
    @result = index.search(query, size: 3)
    @recipes = [ @recipe, Recipe.find(@result[1][:id]), Recipe.find(@result[2][:id]) ]
  end

  def api
    @recipe = Recipe.find(params[:query])
    render json: @recipe
  end

  private

  def find_recipe
    @recipe = Recipe.find(params[:query])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/ingredients/index.html.erb
<% @ingredients.each do |ingredient| %>
  <p>
    <%= ingredient.name %><br>
  </p>
  <p>
    Energy: <%= ingredient.energy %><br>
    Carbohydrates: <%= ingredient.carbs %><br>
    Fat: <%= ingredient.fat %><br>
    Protein: <%= ingredient.protein %><br>
    Fibre: <%= ingredient.fibre %>
  </p>
  <% nutrition = { Carbohydrates: ingredient.carbs, Fat: ingredient.fat, Protein: ingredient.protein } %>
  <%= pie_chart nutrition, donut: true, defer: true %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>IntelliFood</title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>

  </head>

  <body>

    <%= render 'shared/navbar' %>

    <%= yield %>

    <%= render 'shared/flashes' %>

  </body>
</html>

app/views/pages/home.html.erb
<div class="container">

  <%= render "shared/search_form" %>

</div>

app/views/recipes/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-6 offset-3 py-3">
      <% @result.each do |r| %>
        <%= r %><br>
      <% end %>
    </div>
  </div>
  <div class="col-12">
    <% @recipes.each_with_index do |recipe, index| %>
      <div class="row">
        <div class="col-6">
          <p>
            <%= recipe.name %><br>
            <%= recipe.category %><br>
            <%= recipe.url %><br>
          </p>
          <p>
            <% nutrient_hash = Hash.new(0) %>
            <% recipe.data["recipe"]["totalDaily"].each do |_, nutrient| %>
              <%= nutrient["label"] %>: <%= nutrient["quantity"].round %>%<br>
              <% nutrient_hash[nutrient["label"]] = nutrient["quantity"] %>
            <% end %>
          </p>
        </div>
        <div class="col-6">
          <% key_nutrient_hash = { Fat: recipe.fat, Carbs: recipe.carbs, Protein: recipe.protein } %>
          <%= pie_chart key_nutrient_hash, donut: true, defer: true %>
          <%= column_chart nutrient_hash, defer: true %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "#", class: "navbar-brand" do %>
    <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", "#", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Messages", "#", class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Action", "#", class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_search_form.html.erb
<div class="col-6 offset-4 form-inline">
  <%= form_tag recipes_path, method: :get do %>
    <%= text_field_tag :query, params[:query], class: "form-control" %>
    <%= button_tag type: "submit", class: "btn btn-primary" do %>
      <i class="fa fa-search icon"></i>
    <% end %>
  <% end %>
</div>
<div class="col-6 offset-4 form-inline">
  <%= form_tag ingredients_path, method: :get do %>
    <%= text_field_tag :query, params[:query], class: "form-control" %>
    <%= button_tag type: "submit", class: "btn btn-primary" do %>
      <i class="fa fa-search icon"></i>
    <% end %>
  <% end %>
</div>